[package]
name = "glb"
version = "0.1.2"
authors = ["Lyneca <atraguliauniliantauthr@gmail.com>"]

[dependencies]
clap = {version = "~2.27.0", features = ["yaml", "color"]}
serde = "*"
serde_derive = "*"
serde_yaml = "*"
